// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aslozlmjcnxvwzskhtgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzbG96bG1qY254dnd6c2todGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjc0ODksImV4cCI6MjA2NTUwMzQ4OX0.yOfShEp2H4JOg23r7Vmqd15wOwlbhBaCTicpTV2qIcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);